edition = "2021"

newline_style = "Unix"
reorder_imports = true
reorder_modules = true
tab_spaces = 3

# Options that are still unstable.
comment_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_comments = true
wrap_comments = true
