[package]
edition = "2021"
name = "server-2"
version = "0.1.0"

[dependencies]
axum = "0.7.5"
serde = "1.0.204"
serde_json = "1.0.121"
thiserror = "1.0.63"

lib-database = { path = "../../libs/lib-database" }
